### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by freyamade**
The docs are written. @Gelo147 could you just give these a quick look over to make sure they look alright and then we can merge it to master and host the docs online

### CODE REVIEW

**Comment by freyamade** [comment]
Also, turns out I forgot to change the username on my laptop when I changed my username on github, so that's why there are commits from WrathRockeu

**Comment by freyamade** [comment]
Resolves #13

**Comment by Gelo147** [comment]
Sorry about the delay

**Comment by freyamade** [comment]
No worries, thanks for that

**Pull request merged**
